# 画像ビューアの設定ファイル (TOML)
# 数値や文字列の調整はここで行います。

# 画像を分類する際に使用するフォルダパス一覧。
# 表示順に意味がある場合は並び替えてください。
[folders]
paths = [
    "",
    "",
    "",
    ""
]

# アイコンの表示サイズ [幅, 高さ]
icon_size = [
    64,
    64
]

# アプリケーションウィンドウの見た目に関する設定。
[viewer]
title = "画像分類アプリ"
default_geometry = "800x600"
# アプリを再起動した際に自動で開くフォルダ。空文字にすると無効化。
last_opened_directory = ""

# 一覧表示で扱う画像ファイルの拡張子。小文字で指定してください。
[images]
supported_extensions = [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif"
]
